apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-app
  namespace: seldon-system
spec:
  name: seldon-app
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: app 
          image: seldon-app 
    graph:
      name: app
      endpoint:
        type: REST 
      type: MODEL
    name: default
    replicas: 1